<a href="https://colab.research.google.com/github/saulfig/BACKUPS-PROJECTS/blob/main/Cars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python -V

Python 3.11.11

# 1.3 Trabajando con datos

In [2]:
import pandas as pd
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 1000)

In [3]:
dataset = pd.read_csv('db.csv', sep=';')

In [4]:
dataset

,Nombre,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Llantas de aleación', 'Cerraduras electricas...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16
3,DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Llantas de aleación', '4 X 4', 'Central mult...",92612.10
...,...,...,...,...,...,...,...
253,Phantom 2013,Motor V8,2014,27505.0,False,"['Control de estabilidad', 'Piloto automático'...",51759.58
254,Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Asientos de cuero', 'Panel digital', 'Sensor...",51667.06
255,Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Llantas de aleación', 'Control de tracción',...",68934.03
256,Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Aire condicionado', '4 X 4', 'Transmisión au...",122110.90
257,Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimedia', 'Techo panorámico', 'Ve...",90381.47

In [5]:
dataset.dtypes

Nombre          object
Motor           object
Año              int64
Kilometraje    float64
Cero_km           bool
Accesorios      object
Valor          float64
dtype: object

In [6]:
dataset[['Kilometraje','Valor']].describe()

         Kilometraje          Valor
count     197.000000     258.000000
mean    58278.421320   98960.513101
std     35836.733259   29811.932305
min       107.000000   50742.100000
25%     27505.000000   70743.512500
50%     55083.000000   97724.380000
75%     90495.000000  124633.302500
max    119945.000000  149489.920000

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nombre       258 non-null    object
 1   Motor        258 non-null    object
 2   Año          258 non-null    int64
 3   Kilometraje  197 non-null    float64
 4   Cero_km      258 non-null    bool
 5   Accesorios   258 non-null    object
 6   Valor        258 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 12.5+ KB

In [8]:
()

()

In [9]:
1, 2, 3

(1, 2, 3)

In [10]:
nombre = 'Passat'
valor = 153000
(nombre, valor)

('Passat', 153000)

In [11]:
nombres_carros = tuple(['Jetta Variant', 'Passat', 'Crossfox', 'DS5'])
nombres_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [12]:
type(nombres_carros)

tuple

In [20]:
nombres_carros[-1][1]

'Gol'

# 2.3 Iterando en tuplas

In [21]:
nombres_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5')
nombres_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [22]:
for item in nombres_carros:
    print(item)

Jetta Variant
Passat
Crossfox
DS5

### Desempacando tuplas

In [23]:
nombres_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5')
nombres_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [24]:
carro_1, carro_2, carro_3, carro_4 = nombres_carros

In [25]:
carro_1

'Jetta Variant'

In [26]:
carro_2

'Passat'

In [27]:
carro_3

'Crossfox'

In [28]:
carro_4

'DS5'

In [29]:
_, A, _, B = nombres_carros

In [30]:
A

'Passat'

In [31]:
B

'DS5'

In [32]:
_, C, *_ = nombres_carros

In [33]:
C

'Passat'

## *zip()*

https://docs.python.org/3.6/library/functions.html#zip

In [34]:
carros = ['Jetta Variant', 'Passat', 'Crossfox', 'DS5']
carros

['Jetta Variant', 'Passat', 'Crossfox', 'DS5']

In [35]:
valores = [88078.64, 106161.94, 72832.16, 124549.07]
valores

[88078.64, 106161.94, 72832.16, 124549.07]

In [36]:
list(zip(carros, valores))

[('Jetta Variant', 88078.64),
 ('Passat', 106161.94),
 ('Crossfox', 72832.16),
 ('DS5', 124549.07)]

In [37]:
for item in zip(carros, valores):
    print(item)

('Jetta Variant', 88078.64)
('Passat', 106161.94)
('Crossfox', 72832.16)
('DS5', 124549.07)

In [38]:
for carro, valor in zip(carros, valores):
    print(carro, valor)

Jetta Variant 88078.64
Passat 106161.94
Crossfox 72832.16
DS5 124549.07

In [39]:
for carro, valor in zip(carros, valores):
    if(valor > 100000):
        print(carro)

Passat
DS5

In [40]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [41]:
valores = [88078.64, 106161.94, 72832.16]
valores

[88078.64, 106161.94, 72832.16]

In [42]:
carros.index('Passat')

1

In [43]:
valores[carros.index('Passat')]

106161.94

In [44]:
datos = {'Jetta Variant':88078.64, 'Passat':106161.94, 'Crossfox':72832.16}
datos

{'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}

In [45]:
type(datos)

dict

In [46]:
list(zip(carros,valores))

[('Jetta Variant', 88078.64), ('Passat', 106161.94), ('Crossfox', 72832.16)]

In [47]:
datos = dict(zip(carros,valores))
datos

{'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}

In [49]:
'Passat' in datos

True

In [50]:
'Fusca' in datos

False

In [51]:
'Fusca' not in datos

True

In [53]:
datos['DS5'] = 124549.07

## *del dict[ key ]*

Borra el item de llave (*key*) del diccionario.

In [55]:
datos

{'Jetta Variant': 88078.64,
 'Passat': 106161.94,
 'Crossfox': 72832.16,
 'DS5': 124549.07}

In [56]:
del datos['Passat']
datos

{'Jetta Variant': 88078.64, 'Crossfox': 72832.16, 'DS5': 124549.07}

# 3.3 Métodos de diccionarios

## *dict.update()*

Actualiza el diccionario.

In [57]:
datos

{'Jetta Variant': 88078.64, 'Crossfox': 72832.16, 'DS5': 124549.07}

In [58]:
datos.update({'Passat': 106161.94})
datos

{'Jetta Variant': 88078.64,
 'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Passat': 106161.94}

In [59]:
datos.update({'Passat': 106161.95, 'Fusca': 150000})
datos

{'Jetta Variant': 88078.64,
 'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Passat': 106161.95,
 'Fusca': 150000}

## *dict.copy()*

Crea una copia del diccionario.

In [60]:
datosCopy = datos.copy()

In [61]:
datosCopy

{'Jetta Variant': 88078.64,
 'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Passat': 106161.95,
 'Fusca': 150000}

In [62]:
del datosCopy['Fusca']
datosCopy

{'Jetta Variant': 88078.64,
 'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Passat': 106161.95}

In [63]:
datos

{'Jetta Variant': 88078.64,
 'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Passat': 106161.95,
 'Fusca': 150000}

## *dict.pop(key[, default ])*

Si la llave se encuentra en el diccionario, el elemento se elimina y se devuelve su valor. De lo contrario, se devuelve el valor especificado como *default*. Si no se proporciona el valor *default* y la llave no se encuentra en el diccionario, se generará un error.

In [64]:
datosCopy

{'Jetta Variant': 88078.64,
 'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Passat': 106161.95}

In [65]:
datosCopy.pop('Passat')

106161.95

In [66]:
datosCopy

{'Jetta Variant': 88078.64, 'Crossfox': 72832.16, 'DS5': 124549.07}

In [67]:
# datosCopy.pop('Passat')

In [68]:
datosCopy.pop('Passat', 'Llave no encontrada')

'Llave no encontrada'

In [69]:
datosCopy.pop('DS5', 'Llave no encontrada')

124549.07

In [70]:
datosCopy

{'Jetta Variant': 88078.64, 'Crossfox': 72832.16}

## *dict.clear()*

Borra todos los itens del diccionario.

In [71]:
datosCopy.clear()

In [72]:
datosCopy

{}

# 3.4 Iterando en diccionarios

## *dict.keys()*

Devuelve una lista con las llaves (*keys*) del diccionario.

In [73]:
datos.keys()

dict_keys(['Jetta Variant', 'Crossfox', 'DS5', 'Passat', 'Fusca'])

In [74]:
for key in datos.keys():
    print(datos[key])

88078.64
72832.16
124549.07
106161.95
150000

## *dict.values()*

Devuelve una lista con todos los valores (*values*) del diccionario.

In [75]:
datos.values()

dict_values([88078.64, 72832.16, 124549.07, 106161.95, 150000])

## *dict.items()*

Devuelve una lista con una tupla para cada par llave-valor (*key-value*) del diccionario.

In [76]:
datos.items()

dict_items([('Jetta Variant', 88078.64), ('Crossfox', 72832.16), ('DS5', 124549.07), ('Passat', 106161.95), ('Fusca', 150000)])

In [77]:
for item in datos.items():
    print(item)

('Jetta Variant', 88078.64)
('Crossfox', 72832.16)
('DS5', 124549.07)
('Passat', 106161.95)
('Fusca', 150000)

In [78]:
for key, value in datos.items():
    print(key, value)

Jetta Variant 88078.64
Crossfox 72832.16
DS5 124549.07
Passat 106161.95
Fusca 150000

In [79]:
for key, value in datos.items():
    if(value > 100000):
        print(key)

DS5
Passat
Fusca

# <font color=green> 4. FUNCIONES Y PAQUETES
---

Funciones son unidades de código reutilizables que realizan una tarea específica, pueden recibir alguna entrada y también pueden devolver algún resultado.

# 4.1 Built-in function

El lenguaje Python tiene varias funciones integradas que siempre están accesibles. Algunas ya las usamos en nuestro entrenamiento:
type(), print(), zip(), len(), set() etc.

https://docs.python.org/3.6/library/functions.html

In [80]:
datos = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
datos

{'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}

In [81]:
valores = []
for valor in datos.values():
    valores.append(valor)
valores

[88078.64, 106161.94, 72832.16]

In [82]:
suma = 0
for valor in datos.values():
    suma += valor
suma

267072.74

In [83]:
list(datos.values())

[88078.64, 106161.94, 72832.16]

In [84]:
sum(datos.values())

267072.74

In [85]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

In [86]:
print?

# 4.2 Definiendo funciones sin y con parámetros

### Funciones sin parámetros

#### Formato estándar

```
def <nombre>():
    <instrucciones>
```

In [87]:
def media():
    valor = (1 + 2 + 3) / 3
    print(valor)

In [88]:
media()

2.0

### Funciones con parámetros

#### Formato estándar

```
def <nombre>(<param_1>, <param_2>, ..., <param_n>):
    <instrucciones>
```

In [89]:
def media(number_1, number_2, number_3):
    valor = (number_1 + number_2 + number_3) / 3
    print(valor)

In [90]:
media(1, 2, 3)

2.0

In [91]:
media(23, 45, 67)

45.0

In [92]:
def media(lista):
    valor = sum(lista) / len(lista)
    print(valor)

In [93]:
resultado = media([1, 2, 3, 4, 5, 6, 7, 8, 9])

5.0

In [94]:
resultado

In [95]:
type(resultado)

NoneType

# 4.3 Definiendo funciones que devuelven valores

### Funciones que devuelven un valor

#### Formato estándar

```
def <nombre>(<param_1>, <param_2>, ..., <param_n>):
    <instrucciones>
    return <resultado>
```

In [96]:
def media(lista):
    valor = sum(lista) / len(lista)
    print(valor)

In [97]:
media([1, 2, 3, 4, 5, 6, 7, 8])

4.5

In [98]:
resultado = media([1, 2, 3, 4, 5, 6, 7, 8])

4.5

In [99]:
resultado

### Funciones que devuelven más de un valor

#### Formato estándar

```
def <nombre>(<param_1>, <param_2>, ..., <param_n>):
    <instrucciones>
    return (<resultado_1>, <resultado_2>, ..., <resultado_n>)
```

In [100]:
def media(lista):
    valor = sum(lista) / len(lista)
    return (valor, len(lista))

In [101]:
media([1, 2, 3, 4, 5, 6, 7, 8, 9])

(5.0, 9)

In [102]:
resultado, n = media([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
resultado

5.0

In [104]:
n

9

# <font color=green> 5. PANDAS BÁSICO
---

**versión: 1.1.0**

Pandas es una herramienta de manipulación de datos de alto nivel, construida sobre la base del paquete Numpy. El paquete pandas tiene estructuras de datos muy interesantes para la manipulación de datos y, por esto, es ampliamente utilizado por los científicos de datos.


## Estructuras de Datos

### Series

Series son arrays unidimensionales etiquetados capaces de almacenar cualquier tipo de dato. Las etiquetas de las líneas se denominan **index**. La forma básica de crear una Series es la siguiente:


```
    s = pd.Series(datos, index = index)
```

El argumento *datos* puede ser un diccionario, una lista, un array Numpy o una constante.

### DataFrames

DataFrame es una estructura de datos tabular bidimensional con etiquetas de fila y columna. Como la Series, los DataFrames son capaces de almacenar cualquier tipo de datos.


```
    df = pd.DataFrame(datos, index = index, columns = columns)
```

El argumento *datos* puede ser un diccionario, una lista, un array Numpy, una Series y otro DataFrame.

**Documentación:** https://pandas.pydata.org/pandas-docs/version/1.1.0/

# 5.1 Estructuras de datos

In [105]:
import pandas as pd

### Creando una Series a partir de una lista

In [106]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [107]:
pd.Series(carros)

0    Jetta Variant
1           Passat
2         Crossfox
dtype: object

### Creando un DataFrame a partir de una lista de diccionarios

In [108]:
datos = [
    {'Nombre': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Año': 2003, 'Kilometraje': 44410.0, 'Cero_km': False, 'Valor': 88078.64},
    {'Nombre': 'Passat', 'Motor': 'Motor Diesel', 'Año': 1991, 'Kilometraje': 5712.0, 'Cero_km': False, 'Valor': 106161.94},
    {'Nombre': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Año': 1990, 'Kilometraje': 37123.0, 'Cero_km': False, 'Valor': 72832.16}
]

In [109]:
dataset = pd.DataFrame(datos)

In [110]:
dataset

          Nombre            Motor   Año  Kilometraje  Cero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003      44410.0    False   88078.64
1         Passat     Motor Diesel  1991       5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990      37123.0    False   72832.16

In [111]:
dataset[['Nombre','Motor','Año','Kilometraje','Cero_km','Valor']]

          Nombre            Motor   Año  Kilometraje  Cero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003      44410.0    False   88078.64
1         Passat     Motor Diesel  1991       5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990      37123.0    False   72832.16

### Creando un DataFrame a partir de un diccionario

In [112]:
datos = {
    'Nombre': ['Jetta Variant', 'Passat', 'Crossfox'],
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8'],
    'Año': [2003, 1991, 1990],
    'Kilometraje': [44410.0, 5712.0, 37123.0],
    'Cero_km': [False, False, False],
    'Valor': [88078.64, 106161.94, 72832.16]
}

In [113]:
dataset = pd.DataFrame(datos)

In [114]:
dataset

          Nombre            Motor   Año  Kilometraje  Cero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003      44410.0    False   88078.64
1         Passat     Motor Diesel  1991       5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990      37123.0    False   72832.16

### Creando un DataFrame a partir de un archivo externo

In [115]:
dataset = pd.read_csv('db.csv', sep = ';', index_col = 0)

In [116]:
dataset

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Llantas de aleación', 'Cerraduras electricas...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Llantas de aleación', '4 X 4', 'Central mult...",92612.10
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Control de estabilidad', 'Piloto automático'...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Asientos de cuero', 'Panel digital', 'Sensor...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Llantas de aleación', 'Control de tracción',...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Aire condicionado', '4 X 4', 'Transmisión au...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimedia', 'Techo panorámico', 'Ve...",90381.47

# 5.2 Selecciones con DataFrames

In [117]:
dataset.head()

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Llantas de aleación', 'Cerraduras electricas...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Llantas de aleación', '4 X 4', 'Central mult...",92612.10

In [122]:
dataset[0:4]

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Llantas de aleación', 'Cerraduras electricas...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07

### Utilizando .loc para selecciones

<font color=red>**Observación:**</font> Selecciona un grupo de líneas y columnas según las etiquetas o una matriz booleana.

In [123]:
dataset.loc['Passat']

Motor                                               Motor Diesel
Año                                                         1991
Kilometraje                                               5712.0
Cero_km                                                    False
Accesorios     ['Central multimedia', 'Techo panorámico', 'Fr...
Valor                                                  106161.94
Name: Passat, dtype: object

In [124]:
dataset.loc[['Passat', 'DS5']]

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07

In [125]:
dataset.loc[['Passat', 'DS5'], ['Motor', 'Valor']]

                  Motor      Valor
Nombre
Passat     Motor Diesel  106161.94
DS5     Motor 2.4 Turbo  124549.07

In [126]:
dataset.loc[:, ['Motor', 'Valor']]

                                       Motor      Valor
Nombre
Jetta Variant                Motor 4.0 Turbo   88078.64
Passat                          Motor Diesel  106161.94
Crossfox                     Motor Diesel V8   72832.16
DS5                          Motor 2.4 Turbo  124549.07
Aston Martin DB4             Motor 2.4 Turbo   92612.10
...                                      ...        ...
Phantom 2013                        Motor V8   51759.58
Cadillac Ciel concept               Motor V8   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo   68934.03
Aston Martin DB5                Motor Diesel  122110.90
Macan                        Motor Diesel V6   90381.47

[258 rows x 2 columns]

### Utilizando .iloc para selecciones

<font color=red>**Observación:**</font> Selecciona con base en los índices, es decir, utiliza la posición de las informaciones.

In [127]:
dataset.iloc[[1]]

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94

In [128]:
dataset.iloc[1:4]

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07

In [129]:
dataset.iloc[1:4, [0, 5, 2]]

                    Motor      Valor  Kilometraje
Nombre
Passat       Motor Diesel  106161.94       5712.0
Crossfox  Motor Diesel V8   72832.16      37123.0
DS5       Motor 2.4 Turbo  124549.07          NaN

In [130]:
dataset.iloc[[1, 42, 22], [0, 5, 2]]

                               Motor      Valor  Kilometraje
Nombre
Passat                  Motor Diesel  106161.94       5712.0
Optima                 Motor 1.8 16v   86641.34          NaN
Lamborghini Obvious  Motor Diesel V6  133529.84      98079.0

In [131]:
dataset.iloc[:, [0, 5, 2]]

                                       Motor      Valor  Kilometraje
Nombre
Jetta Variant                Motor 4.0 Turbo   88078.64      44410.0
Passat                          Motor Diesel  106161.94       5712.0
Crossfox                     Motor Diesel V8   72832.16      37123.0
DS5                          Motor 2.4 Turbo  124549.07          NaN
Aston Martin DB4             Motor 2.4 Turbo   92612.10      25757.0
...                                      ...        ...          ...
Phantom 2013                        Motor V8   51759.58      27505.0
Cadillac Ciel concept               Motor V8   51667.06      29981.0
Classe GLK             Motor 5.0 V8 Bi-Turbo   68934.03      52637.0
Aston Martin DB5                Motor Diesel  122110.90       7685.0
Macan                        Motor Diesel V6   90381.47      50188.0

[258 rows x 3 columns]

# 5.3 Consultas en DataFrames

In [132]:
dataset.head()

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Llantas de aleación', 'Cerraduras electricas...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Llantas de aleación', '4 X 4', 'Central mult...",92612.10

In [133]:
dataset.Motor

Nombre
Jetta Variant                  Motor 4.0 Turbo
Passat                            Motor Diesel
Crossfox                       Motor Diesel V8
DS5                            Motor 2.4 Turbo
Aston Martin DB4               Motor 2.4 Turbo
                                 ...
Phantom 2013                          Motor V8
Cadillac Ciel concept                 Motor V8
Classe GLK               Motor 5.0 V8 Bi-Turbo
Aston Martin DB5                  Motor Diesel
Macan                          Motor Diesel V6
Name: Motor, Length: 258, dtype: object

In [134]:
select = dataset.Motor == 'Motor Diesel'

In [135]:
type(select)

pandas.core.series.Series

In [136]:
dataset[select]

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94
Effa Hafei Picape Baú,Motor Diesel,1991,102959.0,False,"['Control de estabilidad', 'Panel digital', 'V...",125684.65
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de lluvia', 'Cámara de estacionamient...",81399.35
New Fiesta Hatch,Motor Diesel,2017,118895.0,False,"['Sensor de estacionamiento', 'Cerraduras elec...",66007.16
Kangoo Express,Motor Diesel,2007,29132.0,False,"['Asientos de cuero', 'Transmisión automática'...",146716.91
...,...,...,...,...,...,...
Dodge Dakota,Motor Diesel,1993,71544.0,False,"['Control de tracción', 'Sensor de estacionami...",141083.35
i30 CW,Motor Diesel,2015,8497.0,False,"['Sensor de lluvia', 'Ventanas eléctricas', 'C...",73311.75
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Ventanas eléctricas', 'Cerraduras electricas...",67539.79
V60,Motor Diesel,2004,91840.0,False,"['Llantas de aleación', 'Sensor crepuscular', ...",114728.74
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Aire condicionado', '4 X 4', 'Transmisión au...",122110.90

In [137]:
dataset[(dataset.Motor == 'Motor Diesel') & (dataset.Cero_km == True)]

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de lluvia', 'Cámara de estacionamient...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Panel digital', 'Central multimedia', 'Cámar...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Cerraduras electricas', 'Llantas de aleación...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Cerraduras electricas', 'Control de tracción...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Ventanas eléctricas', 'Cerraduras electricas...",67539.79

In [138]:
(dataset.Motor == 'Motor Diesel') & (dataset.Cero_km == True)

Nombre
Jetta Variant            False
Passat                   False
Crossfox                 False
DS5                      False
Aston Martin DB4         False
                         ...
Phantom 2013             False
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5         False
Macan                    False
Length: 258, dtype: bool

### Utilizando el método query

In [139]:
dataset.query('Motor == "Motor Diesel" and Cero_km == True')

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor
Nombre,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de lluvia', 'Cámara de estacionamient...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Panel digital', 'Central multimedia', 'Cámar...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Cerraduras electricas', 'Llantas de aleación...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Cerraduras electricas', 'Control de tracción...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Ventanas eléctricas', 'Cerraduras electricas...",67539.79

# 5.4 Iterando con DataFrames

In [140]:
for item in dataset:
    print(item)

Motor
Año
Kilometraje
Cero_km
Accesorios
Valor

In [141]:
for index, row in dataset.iterrows():
    if(2020 - row['Año'] != 0):
        dataset.loc[index, 'km_media'] = row['Kilometraje'] / (2020 - row['Año'])
    else:
        dataset.loc[index, 'km_media'] = 0

dataset

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor,km_media
Nombre,,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Llantas de aleación', 'Cerraduras electricas...",88078.64,2612.352941
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94,196.965517
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16,1237.433333
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07,NaN
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Llantas de aleación', '4 X 4', 'Central mult...",92612.10,1839.785714
...,...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Control de estabilidad', 'Piloto automático'...",51759.58,4584.166667
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Asientos de cuero', 'Panel digital', 'Sensor...",51667.06,1033.827586
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Llantas de aleación', 'Control de tracción',...",68934.03,2924.277778
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Aire condicionado', '4 X 4', 'Transmisión au...",122110.90,320.208333
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimedia', 'Techo panorámico', 'Ve...",90381.47,1792.428571

# 5.5 Tratamiento de datos

In [142]:
dataset.head()

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor,km_media
Nombre,,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Llantas de aleación', 'Cerraduras electricas...",88078.64,2612.352941
Passat,Motor Diesel,1991,5712.0,False,"['Central multimedia', 'Techo panorámico', 'Fr...",106161.94,196.965517
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Control de estabilidad'...",72832.16,1237.433333
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07,NaN
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Llantas de aleación', '4 X 4', 'Central mult...",92612.10,1839.785714

In [143]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 258 entries, Jetta Variant to Macan
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Motor        258 non-null    object
 1   Año          258 non-null    int64
 2   Kilometraje  197 non-null    float64
 3   Cero_km      258 non-null    bool
 4   Accesorios   258 non-null    object
 5   Valor        258 non-null    float64
 6   km_media     197 non-null    float64
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 22.5+ KB

In [144]:
dataset.Kilometraje.isna()

Nombre
Jetta Variant            False
Passat                   False
Crossfox                 False
DS5                       True
Aston Martin DB4         False
                         ...
Phantom 2013             False
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5         False
Macan                    False
Name: Kilometraje, Length: 258, dtype: bool

In [145]:
dataset[dataset.Kilometraje.isna()]

,Motor,Año,Kilometraje,Cero_km,Accesorios,Valor,km_media
Nombre,,,,,,,
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Cerraduras electricas', '4 X 4', 'Ventanas e...",124549.07,NaN
A5,Motor 4.0 Turbo,2019,NaN,True,"['Transmisión automática', 'Cámara de estacion...",56445.20,NaN
J5,Motor V6,2019,NaN,True,"['Sensor crepuscular', 'Panel digital', 'Llant...",53183.38,NaN
A3,Motor 1.0 8v,2019,NaN,True,"['4 X 4', 'Piloto automático', 'Central multim...",88552.39,NaN
Série 1 M,Motor V8,2019,NaN,True,"['Control de estabilidad', 'Central multimedia...",94564.40,NaN
...,...,...,...,...,...,...,...
Lamborghini Reventón,Motor 4.0 Turbo,2019,NaN,True,"['Control de tracción', 'Aire condicionado', '...",67664.86,NaN
Benni Mini,Motor V8,2019,NaN,True,"['Sensor crepuscular', 'Transmisión automática...",126247.84,NaN
Uno,Motor Diesel V6,2019,NaN,True,"['Central multimedia', 'Sensor crepuscular', '...",128852.21,NaN
Santa Fe,Motor 3.0 32v,2019,NaN,True,"['Cerraduras electricas', 'Aire condicionado',...",129415.33,NaN
XC60,Motor 4.0 Turbo,2019,NaN,True,"['Panel digital', 'Piloto automático', 'Centra...",77675.79,NaN